package admin;


/**
* admin/AdminInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AdminIDL.idl
* Sunday, October 29, 2017 1:08:05 PM EDT
*/

public interface AdminInterface extends AdminInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface AdminInterface
