package admin;


/**
* admin/AdminInterfacePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AdminIDL.idl
* Sunday, October 29, 2017 1:08:04 PM EDT
*/

public abstract class AdminInterfacePOA extends org.omg.PortableServer.Servant
 implements admin.AdminInterfaceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable<String, Integer> _methods = new java.util.Hashtable<String, Integer> ();
  static
  {
    _methods.put ("createRoom", new java.lang.Integer (0));
    _methods.put ("deleteRoom", new java.lang.Integer (1));
    _methods.put ("resetCount", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // admin/AdminInterface/createRoom
       {
         String roomNumber = in.read_string ();
         String date = in.read_string ();
         String list_Of_Time_Slots[] = admin.ListHelper.read (in);
         boolean $result = false;
         $result = this.createRoom (roomNumber, date, list_Of_Time_Slots);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // admin/AdminInterface/deleteRoom
       {
         String roomNumber = in.read_string ();
         String date = in.read_string ();
         String list_Of_Time_Slots[] = admin.ListHelper.read (in);
         boolean $result = false;
         $result = this.deleteRoom (roomNumber, date, list_Of_Time_Slots);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // admin/AdminInterface/resetCount
       {
         boolean $result = false;
         $result = this.resetCount ();
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:admin/AdminInterface:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public AdminInterface _this() 
  {
    return AdminInterfaceHelper.narrow(
    super._this_object());
  }

  public AdminInterface _this(org.omg.CORBA.ORB orb) 
  {
    return AdminInterfaceHelper.narrow(
    super._this_object(orb));
  }


} // class AdminInterfacePOA
