package admin;


/**
* admin/_AdminInterfaceStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AdminIDL.idl
* Friday, December 1, 2017 1:25:00 PM EST
*/

public class _AdminInterfaceStub extends org.omg.CORBA.portable.ObjectImpl implements admin.AdminInterface
{

  public boolean createRoom (String campusName, String roomNumber, String date, String[] list_Of_Time_Slots)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("createRoom", true);
                $out.write_string (campusName);
                $out.write_string (roomNumber);
                $out.write_string (date);
                admin.ListHelper.write ($out, list_Of_Time_Slots);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return createRoom (campusName, roomNumber, date, list_Of_Time_Slots        );
            } finally {
                _releaseReply ($in);
            }
  } // createRoom

  public boolean deleteRoom (String campusName, String roomNumber, String date, String[] list_Of_Time_Slots)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("deleteRoom", true);
                $out.write_string (campusName);
                $out.write_string (roomNumber);
                $out.write_string (date);
                admin.ListHelper.write ($out, list_Of_Time_Slots);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return deleteRoom (campusName, roomNumber, date, list_Of_Time_Slots        );
            } finally {
                _releaseReply ($in);
            }
  } // deleteRoom

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:admin/AdminInterface:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _AdminInterfaceStub
