package admin;


/**
* admin/AdminInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AdminIDL.idl
* Friday, December 1, 2017 1:25:00 PM EST
*/

public interface AdminInterfaceOperations 
{
  boolean createRoom (String campusName, String roomNumber, String date, String[] list_Of_Time_Slots);
  boolean deleteRoom (String campusName, String roomNumber, String date, String[] list_Of_Time_Slots);
} // interface AdminInterfaceOperations
