package admin;


/**
* admin/AdminInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AdminIDL.idl
* Friday, December 1, 2017 1:25:00 PM EST
*/

public interface AdminInterface extends AdminInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface AdminInterface
