package student;


/**
* student/StudentInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StudentIDL.idl
* Friday, December 1, 2017 12:00:27 PM EST
*/

public interface StudentInterface extends StudentInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface StudentInterface
