package student;


/**
* student/StudentInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StudentIDL.idl
* Monday, October 30, 2017 1:14:59 PM EDT
*/

public interface StudentInterface extends StudentInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface StudentInterface
