package student;


/**
* student/StudentInterfaceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StudentIDL.idl
* Monday, October 30, 2017 1:14:59 PM EDT
*/

abstract public class StudentInterfaceHelper
{
  private static String  _id = "IDL:student/StudentInterface:1.0";

  public static void insert (org.omg.CORBA.Any a, student.StudentInterface that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static student.StudentInterface extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (student.StudentInterfaceHelper.id (), "StudentInterface");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static student.StudentInterface read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_StudentInterfaceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, student.StudentInterface value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static student.StudentInterface narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof student.StudentInterface)
      return (student.StudentInterface)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      student._StudentInterfaceStub stub = new student._StudentInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static student.StudentInterface unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof student.StudentInterface)
      return (student.StudentInterface)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      student._StudentInterfaceStub stub = new student._StudentInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
