package student;

/**
* student/StudentInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StudentIDL.idl
* Monday, October 30, 2017 1:14:58 PM EDT
*/

public final class StudentInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public student.StudentInterface value = null;

  public StudentInterfaceHolder ()
  {
  }

  public StudentInterfaceHolder (student.StudentInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = student.StudentInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    student.StudentInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return student.StudentInterfaceHelper.type ();
  }

}
