package student;


/**
* student/StudentInterfacePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StudentIDL.idl
* Monday, October 30, 2017 1:14:58 PM EDT
*/

public abstract class StudentInterfacePOA extends org.omg.PortableServer.Servant
 implements student.StudentInterfaceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("bookRoom", new java.lang.Integer (0));
    _methods.put ("getAvailableTimeSlot", new java.lang.Integer (1));
    _methods.put ("cancelBooking", new java.lang.Integer (2));
    _methods.put ("changeReservation", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // student/StudentInterface/bookRoom
       {
         String campusName = in.read_string ();
         String studentID = in.read_string ();
         String roomNumber = in.read_string ();
         String date = in.read_string ();
         String timeslot = in.read_string ();
         String $result = null;
         $result = this.bookRoom (campusName, studentID, roomNumber, date, timeslot);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // student/StudentInterface/getAvailableTimeSlot
       {
         String date = in.read_string ();
         String $result = null;
         $result = this.getAvailableTimeSlot (date);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // student/StudentInterface/cancelBooking
       {
         String bookingID = in.read_string ();
         String studentID = in.read_string ();
         boolean $result = false;
         $result = this.cancelBooking (bookingID, studentID);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // student/StudentInterface/changeReservation
       {
         String booking_id = in.read_string ();
         String new_campus_name = in.read_string ();
         String new_room_no = in.read_string ();
         String new_time_slot = in.read_string ();
         String studentID = in.read_string ();
         String $result = null;
         $result = this.changeReservation (booking_id, new_campus_name, new_room_no, new_time_slot, studentID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:student/StudentInterface:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public StudentInterface _this() 
  {
    return StudentInterfaceHelper.narrow(
    super._this_object());
  }

  public StudentInterface _this(org.omg.CORBA.ORB orb) 
  {
    return StudentInterfaceHelper.narrow(
    super._this_object(orb));
  }


} // class StudentInterfacePOA
